from __future__ import annotations

# Country name → ISO 3166-1 alpha-2 code mapping
# Covers English library-catalog forms and Hebrew transliterations.

COUNTRY_NAME_TO_CODE: dict[str, str] = {
    # ── Middle East & North Africa ─────────────────────────────────────────────
    "israel": "il",
    "ישראל": "il",
    "jordan": "jo",
    "ירדן": "jo",
    "lebanon": "lb",
    "לבנון": "lb",
    "syria": "sy",
    "סוריה": "sy",
    "egypt": "eg",
    "מצרים": "eg",
    "iraq": "iq",
    "עיראק": "iq",
    "iran": "ir",
    "איראן": "ir",
    "saudi arabia": "sa",
    "ערב הסעודית": "sa",
    "ערב סעודית": "sa",
    "kuwait": "kw",
    "כווית": "kw",
    "bahrain": "bh",
    "בחריין": "bh",
    "qatar": "qa",
    "קטר": "qa",
    "united arab emirates": "ae",
    "איחוד האמירויות": "ae",
    "oman": "om",
    "עומאן": "om",
    "yemen": "ye",
    "תימן": "ye",
    "libya": "ly",
    "לוב": "ly",
    "tunisia": "tn",
    "תוניסיה": "tn",
    "algeria": "dz",
    "אלג'יריה": "dz",
    "אלגריה": "dz",
    "morocco": "ma",
    "מרוקו": "ma",
    "sudan": "sd",
    "סודן": "sd",
    "mauritania": "mr",
    "מאוריטניה": "mr",
    "palestine": "ps",
    "פלסטין": "ps",
    "west bank": "ps",
    "gaza": "ps",
    "cyprus": "cy",
    "קפריסין": "cy",
    "turkey": "tr",
    "טורקיה": "tr",
    "turkiye": "tr",
    # ── Europe ─────────────────────────────────────────────────────────────────
    "greece": "gr",
    "יוון": "gr",
    "italy": "it",
    "איטליה": "it",
    "france": "fr",
    "צרפת": "fr",
    "germany": "de",
    "גרמניה": "de",
    "united kingdom": "gb",
    "בריטניה": "gb",
    "great britain": "gb",
    "england": "gb",
    "scotland": "gb",
    "wales": "gb",
    "spain": "es",
    "ספרד": "es",
    "portugal": "pt",
    "פורטוגל": "pt",
    "netherlands": "nl",
    "הולנד": "nl",
    "the netherlands": "nl",
    "belgium": "be",
    "בלגיה": "be",
    "luxembourg": "lu",
    "לוקסמבורג": "lu",
    "switzerland": "ch",
    "שוויץ": "ch",
    "austria": "at",
    "אוסטריה": "at",
    "sweden": "se",
    "שוודיה": "se",
    "norway": "no",
    "נורווגיה": "no",
    "denmark": "dk",
    "דנמרק": "dk",
    "finland": "fi",
    "פינלנד": "fi",
    "iceland": "is",
    "איסלנד": "is",
    "ireland": "ie",
    "אירלנד": "ie",
    "poland": "pl",
    "פולין": "pl",
    "czech republic": "cz",
    "czechia": "cz",
    "צ'כיה": "cz",
    "slovakia": "sk",
    "סלובקיה": "sk",
    "hungary": "hu",
    "הונגריה": "hu",
    "romania": "ro",
    "רומניה": "ro",
    "bulgaria": "bg",
    "בולגריה": "bg",
    "serbia": "rs",
    "סרביה": "rs",
    "croatia": "hr",
    "קרואטיה": "hr",
    "slovenia": "si",
    "סלובניה": "si",
    "bosnia and herzegovina": "ba",
    "בוסניה": "ba",
    "north macedonia": "mk",
    "macedonia": "mk",
    "albania": "al",
    "אלבניה": "al",
    "ukraine": "ua",
    "אוקראינה": "ua",
    "russia": "ru",
    "רוסיה": "ru",
    "belarus": "by",
    "בלרוס": "by",
    "moldova": "md",
    "מולדובה": "md",
    "estonia": "ee",
    "אסטוניה": "ee",
    "latvia": "lv",
    "לטביה": "lv",
    "lithuania": "lt",
    "ליטא": "lt",
    "armenia": "am",
    "ארמניה": "am",
    "azerbaijan": "az",
    "אזרבייג'ן": "az",
    "georgia": "ge",
    "גאורגיה": "ge",
    "malta": "mt",
    "מלטה": "mt",
    # ── Sub-Saharan Africa ─────────────────────────────────────────────────────
    "ethiopia": "et",
    "אתיופיה": "et",
    "south africa": "za",
    "דרום אפריקה": "za",
    "nigeria": "ng",
    "ניגריה": "ng",
    "kenya": "ke",
    "קניה": "ke",
    "tanzania": "tz",
    "טנזניה": "tz",
    "ghana": "gh",
    "גאנה": "gh",
    "senegal": "sn",
    "סנגל": "sn",
    "somalia": "so",
    "סומליה": "so",
    "eritrea": "er",
    "אריתריאה": "er",
    "djibouti": "dj",
    "ג'יבוטי": "dj",
    # ── Americas ───────────────────────────────────────────────────────────────
    "united states": "us",
    "usa": "us",
    "ארצות הברית": "us",
    "canada": "ca",
    "קנדה": "ca",
    "mexico": "mx",
    "מקסיקו": "mx",
    "brazil": "br",
    "ברזיל": "br",
    "argentina": "ar",
    "ארגנטינה": "ar",
    "chile": "cl",
    "צ'ילה": "cl",
    "colombia": "co",
    "קולומביה": "co",
    "peru": "pe",
    "פרו": "pe",
    "venezuela": "ve",
    "ונצואלה": "ve",
    "cuba": "cu",
    "קובה": "cu",
    # ── Asia-Pacific ───────────────────────────────────────────────────────────
    "china": "cn",
    "סין": "cn",
    "japan": "jp",
    "יפן": "jp",
    "india": "in",
    "הודו": "in",
    "pakistan": "pk",
    "פקיסטן": "pk",
    "afghanistan": "af",
    "אפגניסטן": "af",
    "bangladesh": "bd",
    "בנגלדש": "bd",
    "sri lanka": "lk",
    "סרי לנקה": "lk",
    "nepal": "np",
    "נפאל": "np",
    "myanmar": "mm",
    "burma": "mm",
    "thailand": "th",
    "תאילנד": "th",
    "vietnam": "vn",
    "וייטנאם": "vn",
    "cambodia": "kh",
    "קמבודיה": "kh",
    "laos": "la",
    "לאוס": "la",
    "malaysia": "my",
    "מלזיה": "my",
    "indonesia": "id",
    "אינדונזיה": "id",
    "philippines": "ph",
    "פיליפינים": "ph",
    "south korea": "kr",
    "korea": "kr",
    "קוריאה": "kr",
    "north korea": "kp",
    "taiwan": "tw",
    "טייוואן": "tw",
    "mongolia": "mn",
    "מונגוליה": "mn",
    "kazakhstan": "kz",
    "קזחסטן": "kz",
    "uzbekistan": "uz",
    "אוזבקיסטן": "uz",
    "australia": "au",
    "אוסטרליה": "au",
    "new zealand": "nz",
    "ניו זילנד": "nz",
}

CODE_TO_NAME: dict[str, str] = {v: k for k, v in COUNTRY_NAME_TO_CODE.items() if k.isascii()}


def detect_country_code(cell: str | None) -> str | None:
    """
    Parse the first $$a value in a MARC 151 cell and look up the country
    from its trailing parenthetical qualifiers.

    "Rekem (Extinct city) (Israel)" → "il"
    "נמרין (ישראל)"                  → "il"
    "Paris (France)"                 → "fr"
    Returns None when no country qualifier is recognised.
    """
    import re
    if not isinstance(cell, str):
        return None
    m = re.search(r'\$\$a(.+?)(?:\$\$|\Z)', cell)
    name = m.group(1).strip() if m else cell.strip()
    parens = re.findall(r'\(([^)]+)\)', name)
    for p in reversed(parens):
        code = COUNTRY_NAME_TO_CODE.get(p.strip().lower())
        if code:
            return code
        code = COUNTRY_NAME_TO_CODE.get(p.strip())
        if code:
            return code
    return None
